#ifndef _ENUMS_
#define _ENUMS_

enum pmode{NORMAL_GAMEPLAY = 0, MAP_EDITOR = 1, TILESET_EDITOR = 2};
enum movper{MOVEMENT_WALKABLE = 0, MOVEMENT_BLOCKED = 1, MOVEMENT_LAYER0 = 2, MOVEMENT_LAYER1 = 3};
enum dir{DIR_DOWN = 0, DIR_LEFT = 1, DIR_RIGHT = 2, DIR_UP = 3};
enum enttype{ENTTYPE_PLAYER, ENTTYPE_NPC, ENTTYPE_ITEM, ENTTYPE_SIGN, ENTTYPE_SCRIPT, ENTTYPE_WARP};
enum entstate{ENTSTATE_NONE, ENTSTATE_MOVING, ENTSTATE_TURNING, ENTSTATE_WAITING};

#endif
